// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvYo89C7LTrkcIyNp-rzN9vTYXxzhVtPc',
    appId: '1:811721817861:web:4d6994535adcbbe757816c',
    messagingSenderId: '811721817861',
    projectId: 'exchangeapp-1432',
    authDomain: 'exchangeapp-1432.firebaseapp.com',
    storageBucket: 'exchangeapp-1432.appspot.com',
    measurementId: 'G-3METRTVRQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdB1S0PM0ZyEYZjRepj9iOYfz8uAeQcXI',
    appId: '1:811721817861:android:ac0151ef820906d257816c',
    messagingSenderId: '811721817861',
    projectId: 'exchangeapp-1432',
    storageBucket: 'exchangeapp-1432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXj-tzhFtHZwJJ9MH514XQaEUtTrliXEI',
    appId: '1:811721817861:ios:0af5aa6535db0ef157816c',
    messagingSenderId: '811721817861',
    projectId: 'exchangeapp-1432',
    storageBucket: 'exchangeapp-1432.appspot.com',
    iosBundleId: 'com.example.studyglide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXj-tzhFtHZwJJ9MH514XQaEUtTrliXEI',
    appId: '1:811721817861:ios:0af5aa6535db0ef157816c',
    messagingSenderId: '811721817861',
    projectId: 'exchangeapp-1432',
    storageBucket: 'exchangeapp-1432.appspot.com',
    iosBundleId: 'com.example.studyglide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvYo89C7LTrkcIyNp-rzN9vTYXxzhVtPc',
    appId: '1:811721817861:web:85f6b2e1f55bb56357816c',
    messagingSenderId: '811721817861',
    projectId: 'exchangeapp-1432',
    authDomain: 'exchangeapp-1432.firebaseapp.com',
    storageBucket: 'exchangeapp-1432.appspot.com',
    measurementId: 'G-EY5YJSF8C8',
  );
}
